### ISSUE TITLE
Créditos README-cards-stars

### ISSUE THREAD

**Issue by bpires** [iuricode/readme-template#19]
Hey Iuri 👋🏻 

Primeiramente, parabéns pela iniciativa em disponibilizar templates de READMEs, isso ajuda demais na visibilidade dos nossos projetos e perfis! 👏🏻 

Algo que queria trazer tua reflexão é em relação aos créditos das funcionalidades, em especial o [README-cards-stars](https://github.com/iuricode/README-template/blob/main/README-cards-stars/cards-stars.md).

Como um entusiasta da filosofia open source, me chamou a atenção você não dar os créditos devidos ao Anurag Hazra, criador do [GitHub Readme Stats](https://github.com/anuraghazra/github-readme-stats).

Embora o uso desses stats cards seja altamente difundido, dando crédito ao desenvolvedor nós valorizamos o trabalho dele e fortalecemos a filosofia colaborativa da rede open source.

Você pode fazer isso colocando uma referência ao repositório original.
Ou seja, em vez de colocar um link ao seu repo:
`[![card](https://github-readme-stats.vercel.app/api?username=iuricode&theme=default)](https://github.com/iuricode/)`

Você poderia colocar:
`[![card](https://github-readme-stats.vercel.app/api?username=iuricode&theme=default)](https://github.com/anuraghazra/github-readme-stats)`

Assim, quem se interessar pelo card irá ao repositório original de quem desenvolveu.

Outra forma seria pelo menos fazer referência ao projeto no seu README, como é sugerido no [README do projeto original](https://github.com/anuraghazra/github-readme-stats/blob/master/docs/readme_pt-BR.md):

> 💖 Apoie o projeto
> Disponibilizo como código aberto quase tudo o que posso e tento responder a todos que precisam de ajuda para utilizar esses projetos. Claro, isso demanda tempo. Utilize este serviço gratuitamente.
> 
> **No entanto, se você utilizar este projeto e estiver satisfeito com ele, ou apenas quiser me encorajar a continuar criando coisas, existem algumas formas fazê-lo:**
> 
> **Dando os devidos créditos ao usar github-readme-stats no seu README.me, adicionando uma referência ao projeto :D**
> Dando uma estrela (Starring) e compartilhando o projeto 🚀
> paypal.me/anuraghazra - Você pode fazer doações únicas via PayPal. Provavelmente vou comprar um café chá. 🍵
> Obrigado! ❤️

Um pequeno gesto conta muito!

Keep going 🔥 

Grande abraço!

**Comment by iuricode** [comment]
Olá Rafael!

Obrigado pela solicitação dos créditos. Já fiz as alterações no README dando os devidos créditos pela criação dos README Stats ao Anurag Hazra.

A comunidade e eu agradecemos pelo apoio ao mundo open source.

Até, Iuri Silva.
