### ISSUE TITLE
Buttons in profile1.md don't work

### ISSUE THREAD

**Issue by joaogdfaero** [iuricode/readme-template#25]
The social media buttons don't work when i try to add my social media links:
![image](https://user-images.githubusercontent.com/103076610/191579415-718d2b3a-579b-4e9c-8f15-85a630471cf2.png)

My Linkedin profile link per example:
![image](https://user-images.githubusercontent.com/103076610/191579615-93500a9b-ec18-4711-94a6-dc29783a247e.png)

When i click the button on my profile it doesn't open the link.

Thanks.

**Comment by iuricode** [comment]
Olá! Você deve colocar o link do seu Linkedin no "href" dentro da tag "a"
